language: node_js
node_js:
    - 0.10
    - 0.12
script: npm run travis
notifications:
    email:
        recipients:
            - ypt-team@yahoo-inc.com
        on_success: change
        on_failure: always
env:
  global:
    - secure: dtJpzQPi6/UYsySz8cUIxja7JiiEvDhtKkKpSZa3skB1Es1NNo/tYmVHZyw4MkLpdvXuJx0020dR5ao7UTag9CZspeSimqmr5Q4AV3eBv7Da6d36Gtm5SCGfWHXTldbPYL19ai1EWPSiifQbWxlN3gew9awCFgoBvOKcZoSJQ1M=
    - secure: Rt/5r/rYFrlPApkVRm2eWvpIJ3ZlLi45LmJVwVp7ruEihxnO4zbjRcO++Co2zhKkjZKHbM/zDiLHGNyPt1GGAjJKdtVyPzMdEvd9Jx8G2J938UoWCAsI7q5twrP96dQcgIsya7LXNlYxnAw5P5jaFJB2ipktk3VHlm/qZXkEgSc=
