[workspace]
members = [
  "crates/icu_skeleton_parser",
  "crates/icu_messageformat_parser",
  "crates/formatjs_cli",
  "packages/icu-messageformat-parser/integration-tests",
]
resolver = "3"

[workspace.dependencies]
pretty_assertions = "1.4"
