sudo: false
language: node_js
node_js:
  - 8
  - 10
  - 12
before_script: npm run build
script: npm test
after_success:
  - "npm run cover"
  - "npm run cover:collect"
  - "cat artifacts/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
