[package]
name = "icu-skeleton-parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "icu_skeleton_parser"
path = "lib.rs"

[dependencies]
once_cell = "1.21.3"
regex = "1.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
