[package]
name = "icu-messageformat-parser-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
icu-messageformat-parser = { path = "../rust" }
serde_json = "1.0"
pretty_assertions = { workspace = true }

[lib]
name = "integration_tests"
path = "integration_tests.rs"
