[package]
name = "formatjs_icu_messageformat_parser_integration_tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
formatjs_icu_messageformat_parser = { path = "../../../rust/icu_messageformat_parser" }
serde_json = "1.0"
pretty_assertions = { workspace = true }

[lib]
name = "integration_tests"
path = "integration_tests.rs"
