name: Deploy Docusaurus to Organization GitHub Pages

on:
  push:
    branches:
      - main # The branch where updates are made in the source repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      # Build the Docusaurus site
      - name: Build Docusaurus Site
        id: build
        run: |
          BAZEL_BIN=$(bazel info bazel-bin)
          bazel build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} //website:dist
          echo BUILD_PATH="$BAZEL_BIN/website/dist" >> $GITHUB_OUTPUTS

      # Deploy to Organization GitHub Pages Repository
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.WEBSITE_SECRET_KEY }}
          external_repository: formatjs/formatjs.github.io
          publish_branch: main # default: gh-pages
          publish_dir: ${{ steps.build.outputs.BUILD_PATH }}
